export const REVIEW_FACT_KEYS = [
  'productType',
  'source',
  'applicationType',
  'distinctiveBottleRequested',
  'destinationState',
  'alcoholContent',
  'containerVolumeMl',
  'brandName',
  'fancifulName',
  'applicantName',
  'applicantAddress',
  'permitName',
  'permitAddress',
  'formulaRequired',
  'formulaId',
  'formulaClassType',
  'formulaCompositionStatement',
  'formulaLabelingInstructions',
  'labelClassType',
  'netContents',
  'labelDimensions',
  'labelSet',
  'bottleMarkings',
  'bottleDesignEvidence',
  'labelAlcoholStatementPresent',
  'containsSignificantSolids',
  'containsNeutralSpirits',
  'requiresAgeStatement',
  'spiritsAgeOrMaturityClaim',
  'requiresWoodTreatmentDisclosure',
  'requiresStateOfDistillation',
  'containsYellow5',
  'containsCochinealOrCarmine',
  'sulfitesPpm',
  'containsAspartame',
  'wineAppellation',
  'wineVarietals',
  'wineVintage',
  'wineEstateBottledClaim',
  'wineForeignBlendReferenced',
  'wineForeignPercentage',
  'maltAlcoholFromAddedIngredients',
  'maltAlcoholCharacterizationClaim',
  'maltGeographicClaim',
  'maltSpecialtyProduct',
  'importCountryOfOrigin',
  'importBottlingDisposition',
  'productionFacts',
] as const

export type ReviewFactKey = (typeof REVIEW_FACT_KEYS)[number]
export type BeverageType = 'distilled_spirits' | 'wine' | 'malt_beverage'
export type ProductSource = 'domestic' | 'imported'
export type RuleCategory = 'common' | BeverageType
export type EvidenceSource =
  | 'form_5100_31'
  | 'colas_online'
  | 'formula'
  | 'permit_or_brewers_notice'
  | 'supporting_document'
  | 'label_artwork'
  | 'derived'

export type ApplicabilityCondition = {
  fact: ReviewFactKey
  operator: 'equals' | 'not_equals' | 'gte' | 'gt' | 'lte' | 'present'
  value?: string | number | boolean
}

export type RuleSpecification = {
  id: string
  category: RuleCategory
  title: string
  requirement: string
  authorities: readonly string[]
  appliesWhen: {
    description: string
    all?: readonly ApplicabilityCondition[]
    any?: readonly ApplicabilityCondition[]
  }
  requiredFacts: readonly ReviewFactKey[]
  evidenceSources: readonly EvidenceSource[]
  evaluation: readonly string[]
  missingContext: string
  reviewerCard: true
}

export type RuleSetSpecification = {
  id: string
  label: string
  description: string
  productType: BeverageType
  source: ProductSource | 'either'
  jurisdiction: 'full_cola_review' | 'ttb_routing_only'
  selectionFacts: readonly ReviewFactKey[]
  baseRuleIds: readonly string[]
  conditionalRuleIds: readonly string[]
}

export type ApplicationDataSpecification = {
  label: string
  sources: readonly EvidenceSource[]
  purpose: string
}

export const APPLICATION_DATA_SPECIFICATIONS = {
  productType: { label: 'Type of product', sources: ['form_5100_31', 'colas_online'], purpose: 'Selects the beverage-category rule family.' },
  source: { label: 'Source of product', sources: ['form_5100_31', 'colas_online'], purpose: 'Selects domestic or imported branches.' },
  applicationType: { label: 'Type of application', sources: ['form_5100_31', 'colas_online'], purpose: 'Activates COLA, exemption, distinctive-bottle, or resubmission behavior.' },
  distinctiveBottleRequested: { label: 'Distinctive liquor bottle request', sources: ['form_5100_31', 'colas_online'], purpose: 'Activates bottle-design consistency review for distilled spirits.' },
  destinationState: { label: 'Exemption destination State', sources: ['form_5100_31', 'colas_online'], purpose: 'Supplies the State for an intrastate exemption statement.' },
  alcoholContent: { label: 'Actual/application alcohol content', sources: ['colas_online', 'formula', 'supporting_document'], purpose: 'Routes wine jurisdiction and controls ABV comparisons and warning applicability.' },
  containerVolumeMl: { label: 'Container capacity', sources: ['colas_online', 'derived'], purpose: 'Selects physical-format thresholds.' },
  brandName: { label: 'Brand name', sources: ['form_5100_31', 'colas_online'], purpose: 'Supplies the authoritative application value for artwork comparison.' },
  fancifulName: { label: 'Fanciful name', sources: ['form_5100_31', 'colas_online'], purpose: 'Supplies the application value for optional or required specialty identity.' },
  applicantName: { label: 'Applicant name', sources: ['form_5100_31', 'colas_online'], purpose: 'Identifies the applicant and possible responsible party.' },
  applicantAddress: { label: 'Applicant address', sources: ['form_5100_31', 'colas_online'], purpose: 'Supplies application address context.' },
  permitName: { label: 'Permit or Brewer’s Notice name/trade name', sources: ['permit_or_brewers_notice'], purpose: 'Provides the authoritative responsible-party name.' },
  permitAddress: { label: 'Permit or Brewer’s Notice address', sources: ['permit_or_brewers_notice'], purpose: 'Provides the authoritative city and State.' },
  formulaRequired: { label: 'Formula requirement', sources: ['formula', 'derived'], purpose: 'Determines whether approved formula evidence is mandatory.' },
  formulaId: { label: 'Formula ID', sources: ['form_5100_31', 'colas_online'], purpose: 'Links the COLA application to its approved formula.' },
  formulaClassType: { label: 'Approved formula class/type', sources: ['formula'], purpose: 'Provides authoritative identity when a formula governs the product.' },
  formulaCompositionStatement: { label: 'Approved composition statement', sources: ['formula'], purpose: 'Provides required or suggested label wording.' },
  formulaLabelingInstructions: { label: 'Formula labeling instructions', sources: ['formula'], purpose: 'Supplies all formula-directed disclosures and restrictions.' },
  labelClassType: { label: 'Detected label class/type', sources: ['label_artwork', 'derived'], purpose: 'Identifies the artwork designation for regulatory and formula comparison.' },
  netContents: { label: 'Application net contents', sources: ['colas_online'], purpose: 'Provides permitted container sizes for artwork comparison.' },
  labelDimensions: { label: 'Printed label dimensions', sources: ['colas_online'], purpose: 'Supports physical type-size and density estimates.' },
  labelSet: { label: 'Complete submitted label set', sources: ['colas_online', 'label_artwork'], purpose: 'Provides every label face and label role for the review.' },
  bottleMarkings: { label: 'Blown, embossed, molded, or applied information', sources: ['form_5100_31', 'colas_online', 'label_artwork'], purpose: 'Adds mandatory information that is not printed on an attached label.' },
  bottleDesignEvidence: { label: 'Distinctive bottle design evidence', sources: ['form_5100_31', 'colas_online', 'label_artwork'], purpose: 'Provides the bottle views and dimensions needed for distinctive-container review.' },
  labelAlcoholStatementPresent: { label: 'Alcohol statement detected on artwork', sources: ['label_artwork', 'derived'], purpose: 'Activates validation of an optional malt beverage alcohol statement.' },
  containsSignificantSolids: { label: 'Significant solid material', sources: ['formula', 'label_artwork'], purpose: 'Activates special distilled-spirits alcohol wording.' },
  containsNeutralSpirits: { label: 'Neutral spirits composition', sources: ['formula'], purpose: 'Activates percentage and commodity disclosures.' },
  requiresAgeStatement: { label: 'Mandatory age-statement determination', sources: ['formula', 'supporting_document', 'derived'], purpose: 'Activates distilled-spirits age rules.' },
  spiritsAgeOrMaturityClaim: { label: 'Detected spirits age/maturity claim', sources: ['label_artwork', 'derived'], purpose: 'Activates validation of optional age and maturity representations.' },
  requiresWoodTreatmentDisclosure: { label: 'Wood-treatment disclosure determination', sources: ['formula', 'supporting_document', 'derived'], purpose: 'Activates distilled-spirits wood-treatment labeling.' },
  requiresStateOfDistillation: { label: 'State-of-distillation determination', sources: ['permit_or_brewers_notice', 'supporting_document', 'derived'], purpose: 'Activates the affected American whisky rule.' },
  containsYellow5: { label: 'FD&C Yellow No. 5 presence', sources: ['formula'], purpose: 'Activates the specific color declaration.' },
  containsCochinealOrCarmine: { label: 'Cochineal extract or carmine presence', sources: ['formula'], purpose: 'Activates the specific color declaration.' },
  sulfitesPpm: { label: 'Total sulfur dioxide', sources: ['formula', 'supporting_document'], purpose: 'Activates sulfite labeling at 10 ppm.' },
  containsAspartame: { label: 'Aspartame presence', sources: ['formula'], purpose: 'Activates the aspartame declaration.' },
  wineAppellation: { label: 'Wine appellation', sources: ['form_5100_31', 'colas_online', 'label_artwork'], purpose: 'Supplies and activates appellation review.' },
  wineVarietals: { label: 'Wine grape varietals', sources: ['form_5100_31', 'colas_online', 'supporting_document'], purpose: 'Activates varietal and appellation rules.' },
  wineVintage: { label: 'Wine vintage', sources: ['colas_online', 'supporting_document'], purpose: 'Activates vintage and appellation rules.' },
  wineEstateBottledClaim: { label: 'Estate bottled claim', sources: ['label_artwork', 'derived'], purpose: 'Activates the estate-production rule.' },
  wineForeignBlendReferenced: { label: 'American/foreign blend reference', sources: ['formula', 'label_artwork', 'derived'], purpose: 'Activates the foreign-wine percentage rule.' },
  wineForeignPercentage: { label: 'Foreign wine percentage', sources: ['formula', 'supporting_document'], purpose: 'Provides the authoritative blend percentage.' },
  maltAlcoholFromAddedIngredients: { label: 'Alcohol from added flavor/non-beverage ingredients', sources: ['formula'], purpose: 'Determines whether malt beverage ABV is mandatory.' },
  maltAlcoholCharacterizationClaim: { label: 'Low/non-alcoholic/alcohol-free claim', sources: ['label_artwork', 'derived'], purpose: 'Activates claim-specific ABV thresholds and wording.' },
  maltGeographicClaim: { label: 'Geographically significant malt designation', sources: ['label_artwork', 'derived'], purpose: 'Activates production-location qualification checks.' },
  maltSpecialtyProduct: { label: 'Malt beverage specialty determination', sources: ['formula', 'derived'], purpose: 'Activates fanciful-name and composition requirements.' },
  importCountryOfOrigin: { label: 'Country of origin', sources: ['supporting_document'], purpose: 'Provides the expected origin for imported-product comparison.' },
  importBottlingDisposition: { label: 'Post-import bottling/production disposition', sources: ['supporting_document', 'permit_or_brewers_notice'], purpose: 'Selects imported product responsible-party wording.' },
  productionFacts: { label: 'Composition, origin, production, and aging facts', sources: ['formula', 'permit_or_brewers_notice', 'supporting_document'], purpose: 'Substantiates conditional identity and optional claims.' },
} as const satisfies Record<ReviewFactKey, ApplicationDataSpecification>

const TTB_FORM = 'https://www.ttb.gov/media/70320/download?inline='
const CFR_WARNING = '27 CFR 16.21-16.22'
const DS_GUIDANCE =
  'https://www.ttb.gov/regulated-commodities/beverage-alcohol/distilled-spirits/labeling'
const DS_DETAIL =
  'https://www.ttb.gov/regulated-commodities/beverage-alcohol/distilled-spirits/ds-labeling-home'
const WINE_GUIDANCE = 'https://www.ttb.gov/regulated-commodities/beverage-alcohol/wine/labeling'
const WINE_DETAIL =
  'https://www.ttb.gov/regulated-commodities/beverage-alcohol/wine/labeling-wine'
const MALT_GUIDANCE = 'https://www.ttb.gov/regulated-commodities/beverage-alcohol/beer/labeling'

const always = { description: 'Every review in this rule category.' } as const

export const RULE_SPECIFICATIONS = [
  {
    id: 'common.label-set-completeness',
    category: 'common',
    title: 'Complete label and container evidence',
    requirement: 'Review every submitted label and any mandatory information blown, embossed, molded, or otherwise applied to the container.',
    authorities: [TTB_FORM, '27 CFR 4.10, 5.61, and 7.61'],
    appliesWhen: always,
    requiredFacts: ['labelSet', 'bottleMarkings'],
    evidenceSources: ['form_5100_31', 'colas_online', 'label_artwork'],
    evaluation: ['Inventory all artwork and Item 15/container markings.', 'Flag missing, unreadable, or internally inconsistent evidence.'],
    missingContext: 'Recommend Fail when the application omits label evidence needed to complete the review.',
    reviewerCard: true,
  },
  {
    id: 'common.health-warning-wording',
    category: 'common',
    title: 'Government warning presence and wording',
    requirement: 'The exact government warning must appear on beverages intended for human consumption containing at least 0.5 percent alcohol by volume.',
    authorities: [CFR_WARNING],
    appliesWhen: { description: 'Alcohol content is at least 0.5% by volume.', all: [{ fact: 'alcoholContent', operator: 'gte', value: 0.5 }] },
    requiredFacts: ['alcoholContent', 'labelSet'],
    evidenceSources: ['colas_online', 'label_artwork'],
    evaluation: ['Search across the complete label set.', 'Compare wording, punctuation, numbering, and capitalization with the prescribed statement.'],
    missingContext: 'Request the missing ABV or artwork; do not silently omit the warning rule.',
    reviewerCard: true,
  },
  {
    id: 'common.health-warning-format',
    category: 'common',
    title: 'Government warning format',
    requirement: 'The heading, body weight, type size, character density, contrast, and separation must satisfy 27 CFR 16.22.',
    authorities: [CFR_WARNING],
    appliesWhen: { description: 'Alcohol content is at least 0.5% by volume.', all: [{ fact: 'alcoholContent', operator: 'gte', value: 0.5 }] },
    requiredFacts: ['alcoholContent', 'containerVolumeMl', 'labelDimensions', 'labelSet'],
    evidenceSources: ['colas_online', 'label_artwork', 'derived'],
    evaluation: ['Select the container-dependent thresholds.', 'Use label dimensions and image geometry to estimate physical size.', 'Evaluate heading capitalization and weight, body weight, density, contrast, and separation.'],
    missingContext: 'State exactly which physical measurements cannot be resolved and still provide the strongest supported recommendation.',
    reviewerCard: true,
  },
  {
    id: 'common.formula-labeling-instructions',
    category: 'common',
    title: 'Approved formula labeling instructions',
    requirement: 'When formula approval is required, the label must follow the approved determination and labeling instructions.',
    authorities: [TTB_FORM, '27 CFR parts 4, 5, 7, 19, 24, and 25 as applicable'],
    appliesWhen: { description: 'The product requires an approved formula.', all: [{ fact: 'formulaRequired', operator: 'equals', value: true }] },
    requiredFacts: ['formulaRequired', 'formulaId', 'formulaLabelingInstructions', 'labelSet'],
    evidenceSources: ['form_5100_31', 'colas_online', 'formula', 'label_artwork'],
    evaluation: ['Verify the formula identity.', 'Turn every labeling instruction into an artwork comparison.', 'Flag omitted or contradictory required language.'],
    missingContext: 'Recommend Fail when a required approved formula or its labeling instructions are absent from the review packet.',
    reviewerCard: true,
  },
  {
    id: 'common.exemption-eligibility',
    category: 'common',
    title: 'Certificate-of-exemption eligibility',
    requirement: 'A certificate of exemption is unavailable for products imported in bottles and for malt beverages.',
    authorities: [TTB_FORM],
    appliesWhen: { description: 'The application requests a certificate of exemption.', all: [{ fact: 'applicationType', operator: 'equals', value: 'exemption' }] },
    requiredFacts: ['applicationType', 'productType', 'source'],
    evidenceSources: ['form_5100_31', 'colas_online', 'derived'],
    evaluation: ['Confirm the product is eligible before evaluating the State-limitation statement.'],
    missingContext: 'Require product type and source before accepting an exemption application.',
    reviewerCard: true,
  },
  {
    id: 'common.exemption-state-limitation',
    category: 'common',
    title: 'Certificate-of-exemption State limitation',
    requirement: 'A qualifying certificate-of-exemption label must state “For sale in [State] only.”',
    authorities: [TTB_FORM],
    appliesWhen: { description: 'The application requests a certificate of exemption.', all: [{ fact: 'applicationType', operator: 'equals', value: 'exemption' }] },
    requiredFacts: ['applicationType', 'destinationState', 'labelSet'],
    evidenceSources: ['form_5100_31', 'colas_online', 'label_artwork'],
    evaluation: ['Compare the destination State with the limitation statement on every container.'],
    missingContext: 'Recommend Fail if the State or required limitation statement is missing.',
    reviewerCard: true,
  },
  {
    id: 'common.optional-information',
    category: 'common',
    title: 'Optional statements, claims, and graphics',
    requirement: 'Optional information must be truthful, accurate, specific, non-misleading, and must not contradict or obscure mandatory information.',
    authorities: ['27 CFR 4.38-4.39, part 5 subpart H, and part 7 subparts F-H'],
    appliesWhen: always,
    requiredFacts: ['labelSet', 'productionFacts'],
    evidenceSources: ['formula', 'supporting_document', 'label_artwork'],
    evaluation: ['Detect textual and graphic claims.', 'Compare claims with formula, origin, age, production, and supporting facts.', 'Activate a more specific claim rule when one exists.'],
    missingContext: 'Identify the unsupported claim and request substantiation rather than presuming it is true.',
    reviewerCard: true,
  },

  {
    id: 'spirits.distinctive-bottle',
    category: 'distilled_spirits',
    title: 'Distinctive liquor bottle',
    requirement: 'When distinctive liquor bottle approval is requested, the submitted bottle design evidence must be complete and consistent with the application.',
    authorities: [TTB_FORM, '27 CFR part 5 subpart L'],
    appliesWhen: { description: 'The application requests distinctive liquor bottle approval.', all: [{ fact: 'distinctiveBottleRequested', operator: 'equals', value: true }] },
    requiredFacts: ['distinctiveBottleRequested', 'bottleDesignEvidence'],
    evidenceSources: ['form_5100_31', 'colas_online', 'label_artwork'],
    evaluation: ['Verify required bottle views and dimensions are present.', 'Compare the submitted design evidence with the requested bottle approval.'],
    missingContext: 'Recommend Fail when a requested distinctive-bottle review lacks complete design evidence.',
    reviewerCard: true,
  },
  {
    id: 'spirits.brand-name',
    category: 'distilled_spirits',
    title: 'Brand name',
    requirement: 'The brand name must appear, match the application, be legible, and not misrepresent the product.',
    authorities: ['27 CFR 5.64', DS_GUIDANCE],
    appliesWhen: always,
    requiredFacts: ['brandName', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['form_5100_31', 'colas_online', 'label_artwork'],
    evaluation: ['Compare the application brand with artwork.', 'Evaluate minimum type size, legibility, and misleading implications.'],
    missingContext: 'Recommend Fail if the required application brand or label statement is absent.',
    reviewerCard: true,
  },
  {
    id: 'spirits.class-type-designation',
    category: 'distilled_spirits',
    title: 'Class, type, or other designation',
    requirement: 'The label must identify the distilled spirits under the applicable standard of identity or approved specialty designation.',
    authorities: ['27 CFR part 5 subpart I', DS_GUIDANCE],
    appliesWhen: always,
    requiredFacts: ['labelClassType', 'formulaClassType', 'formulaCompositionStatement', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork', 'derived'],
    evaluation: ['Compare label identity with the applicable standard or approved formula.', 'For specialties, compare the fanciful name and statement of composition.'],
    missingContext: 'Use the standard of identity when possible; otherwise identify the missing composition evidence.',
    reviewerCard: true,
  },
  {
    id: 'spirits.alcohol-content',
    category: 'distilled_spirits',
    title: 'Alcohol content',
    requirement: 'All distilled spirits labels must state alcohol by volume in an authorized form; optional proof must be properly related to it.',
    authorities: ['27 CFR 5.65', `${DS_DETAIL}/ds-alcohol-content`],
    appliesWhen: always,
    requiredFacts: ['alcoholContent', 'labelSet'],
    evidenceSources: ['colas_online', 'label_artwork'],
    evaluation: ['Compare labeled and application ABV using the applicable tolerance.', 'Validate authorized abbreviations and any proof relationship.'],
    missingContext: 'Recommend Fail if the application or mandatory label ABV is missing.',
    reviewerCard: true,
  },
  {
    id: 'spirits.same-field-of-vision',
    category: 'distilled_spirits',
    title: 'Same field of vision',
    requirement: 'Brand name, alcohol content, and class/type or other designation must be viewable together without turning the container.',
    authorities: ['27 CFR 5.61', `${DS_DETAIL}/ds-brand-label`],
    appliesWhen: always,
    requiredFacts: ['labelSet'],
    evidenceSources: ['colas_online', 'label_artwork', 'derived'],
    evaluation: ['Identify each required element and its label face.', 'Use label-role and geometry metadata to determine whether the elements share one field of vision.'],
    missingContext: 'Identify missing label-face or container-layout evidence; do not infer co-location from OCR text order alone.',
    reviewerCard: true,
  },
  {
    id: 'spirits.name-address',
    category: 'distilled_spirits',
    title: 'Name and address',
    requirement: 'The required bottler, distiller, processor, or importer identity and city/State must use an authorized phrase and match permit context.',
    authorities: ['27 CFR 5.66-5.68', `${DS_DETAIL}/ds-name-address`],
    appliesWhen: always,
    requiredFacts: ['source', 'applicantName', 'applicantAddress', 'permitName', 'permitAddress', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['form_5100_31', 'permit_or_brewers_notice', 'label_artwork'],
    evaluation: ['Select the domestic or import wording branch.', 'Compare name, trade name, city, State, and explanatory phrase.', 'Evaluate type size and legibility.'],
    missingContext: 'Recommend Fail when the responsible-party or permit context needed for comparison is absent.',
    reviewerCard: true,
  },
  {
    id: 'spirits.net-contents',
    category: 'distilled_spirits',
    title: 'Net contents',
    requirement: 'The container must bear net contents in an authorized format and standard of fill.',
    authorities: ['27 CFR 5.70 and part 5 subpart K', DS_GUIDANCE],
    appliesWhen: always,
    requiredFacts: ['netContents', 'containerVolumeMl', 'labelSet', 'bottleMarkings'],
    evidenceSources: ['colas_online', 'label_artwork'],
    evaluation: ['Search labels and authorized container markings.', 'Normalize units and compare quantity.', 'Validate format and standard of fill.'],
    missingContext: 'Recommend Fail when neither artwork nor documented container markings contain the statement.',
    reviewerCard: true,
  },
  {
    id: 'spirits.country-of-origin',
    category: 'distilled_spirits',
    title: 'Imported-product country of origin',
    requirement: 'Imported distilled spirits must bear a country-of-origin statement consistent with the review packet.',
    authorities: ['27 CFR 5.69', DS_GUIDANCE],
    appliesWhen: { description: 'The distilled spirits are imported.', all: [{ fact: 'source', operator: 'equals', value: 'imported' }] },
    requiredFacts: ['source', 'importCountryOfOrigin', 'labelSet'],
    evidenceSources: ['form_5100_31', 'supporting_document', 'label_artwork'],
    evaluation: ['Detect the origin statement.', 'Compare the named country with application/import context.', 'Flag absence or contradiction without reproducing the full CBP rule set.'],
    missingContext: 'Request the import country; do not treat an unspecified origin as a pass.',
    reviewerCard: true,
  },
  {
    id: 'spirits.specialty-composition',
    category: 'distilled_spirits',
    title: 'Specialty fanciful name and composition',
    requirement: 'A distilled spirits specialty must use the required fanciful name and an adequate formula-consistent statement of composition.',
    authorities: ['27 CFR 5.64 and part 5 subpart I', DS_GUIDANCE],
    appliesWhen: { description: 'The formula supplies a specialty composition statement.', all: [{ fact: 'formulaCompositionStatement', operator: 'present' }] },
    requiredFacts: ['fancifulName', 'formulaCompositionStatement', 'labelSet'],
    evidenceSources: ['form_5100_31', 'formula', 'label_artwork'],
    evaluation: ['Compare fanciful name with the application.', 'Compare artwork composition wording with the formula-approved wording or a more specific acceptable statement.'],
    missingContext: 'Recommend Fail if required specialty identity information is absent.',
    reviewerCard: true,
  },
  {
    id: 'spirits.significant-solids-alcohol',
    category: 'distilled_spirits',
    title: 'Alcohol statement for significant solids',
    requirement: 'A product containing significant solid material must use the prescribed “Bottled at … percent alcohol by volume” form.',
    authorities: ['27 CFR 5.65', `${DS_DETAIL}/ds-alcohol-content`],
    appliesWhen: { description: 'The product contains significant solid material.', all: [{ fact: 'containsSignificantSolids', operator: 'equals', value: true }] },
    requiredFacts: ['containsSignificantSolids', 'alcoholContent', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Verify the special wording and compare the bottling ABV.'],
    missingContext: 'Request formula composition facts when visible solids make the branch plausible but unconfirmed.',
    reviewerCard: true,
  },
  {
    id: 'spirits.neutral-spirits-commodity',
    category: 'distilled_spirits',
    title: 'Neutral spirits and commodity statement',
    requirement: 'Covered products using neutral spirits must disclose the required percentage and commodity from which distilled.',
    authorities: ['27 CFR 5.71', DS_GUIDANCE],
    appliesWhen: { description: 'Neutral spirits disclosure is required by composition and product class.', all: [{ fact: 'containsNeutralSpirits', operator: 'equals', value: true }] },
    requiredFacts: ['containsNeutralSpirits', 'formulaLabelingInstructions', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Compare percentage, commodity, and wording with formula and class requirements.'],
    missingContext: 'Request formula composition rather than assuming neutral spirits are absent.',
    reviewerCard: true,
  },
  {
    id: 'spirits.age-statement',
    category: 'distilled_spirits',
    title: 'Age and maturity statements',
    requirement: 'A required or voluntary age statement must use the applicable form and be supported by production facts.',
    authorities: ['27 CFR 5.74', DS_GUIDANCE],
    appliesWhen: { description: 'An age statement is required or the artwork makes an age or maturity claim.', any: [{ fact: 'requiresAgeStatement', operator: 'equals', value: true }, { fact: 'spiritsAgeOrMaturityClaim', operator: 'equals', value: true }] },
    requiredFacts: ['requiresAgeStatement', 'spiritsAgeOrMaturityClaim', 'productionFacts', 'labelSet'],
    evidenceSources: ['formula', 'supporting_document', 'label_artwork'],
    evaluation: ['Compare stated age with the youngest applicable spirits and required wording.', 'Evaluate nearby maturity representations.'],
    missingContext: 'Identify missing aging facts and do not validate an unsupported age claim.',
    reviewerCard: true,
  },
  {
    id: 'spirits.wood-treatment',
    category: 'distilled_spirits',
    title: 'Wood-treatment disclosure',
    requirement: 'Covered treatment with wood must be disclosed using wording consistent with the production method.',
    authorities: ['27 CFR 5.73', DS_GUIDANCE],
    appliesWhen: { description: 'Production facts require a wood-treatment disclosure.', all: [{ fact: 'requiresWoodTreatmentDisclosure', operator: 'equals', value: true }] },
    requiredFacts: ['requiresWoodTreatmentDisclosure', 'productionFacts', 'labelSet'],
    evidenceSources: ['formula', 'supporting_document', 'label_artwork'],
    evaluation: ['Compare the disclosure with the approved production facts.'],
    missingContext: 'Request the formula or production method when wood treatment is indicated.',
    reviewerCard: true,
  },
  {
    id: 'spirits.state-of-distillation',
    category: 'distilled_spirits',
    title: 'State of distillation',
    requirement: 'Affected American whisky must disclose its State of distillation when required.',
    authorities: ['27 CFR 5.66', DS_GUIDANCE],
    appliesWhen: { description: 'The whisky production and address facts trigger the State-of-distillation requirement.', all: [{ fact: 'requiresStateOfDistillation', operator: 'equals', value: true }] },
    requiredFacts: ['requiresStateOfDistillation', 'productionFacts', 'labelSet'],
    evidenceSources: ['permit_or_brewers_notice', 'supporting_document', 'label_artwork'],
    evaluation: ['Compare the disclosed State with production and address facts.'],
    missingContext: 'Request the distillation and address facts needed to resolve applicability.',
    reviewerCard: true,
  },
  {
    id: 'spirits.yellow-5',
    category: 'distilled_spirits',
    title: 'FD&C Yellow No. 5 disclosure',
    requirement: 'FD&C Yellow No. 5 must be specifically declared when present.',
    authorities: ['27 CFR 5.63 and 5.72', `${DS_DETAIL}/ds-color`],
    appliesWhen: { description: 'The formula contains FD&C Yellow No. 5.', all: [{ fact: 'containsYellow5', operator: 'equals', value: true }] },
    requiredFacts: ['containsYellow5', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Verify the specific declaration, type-size threshold, contrast, and separation.'],
    missingContext: 'Request formula ingredients when color-additive status is unavailable.',
    reviewerCard: true,
  },
  {
    id: 'spirits.cochineal-carmine',
    category: 'distilled_spirits',
    title: 'Cochineal extract or carmine disclosure',
    requirement: 'Cochineal extract or carmine must be specifically declared when present.',
    authorities: ['27 CFR 5.63 and 5.72', `${DS_DETAIL}/ds-color`],
    appliesWhen: { description: 'The formula contains cochineal extract or carmine.', all: [{ fact: 'containsCochinealOrCarmine', operator: 'equals', value: true }] },
    requiredFacts: ['containsCochinealOrCarmine', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Verify the specific declaration, type-size threshold, contrast, and separation.'],
    missingContext: 'Request formula ingredients when color-additive status is unavailable.',
    reviewerCard: true,
  },
  {
    id: 'spirits.sulfites',
    category: 'distilled_spirits',
    title: 'Sulfite declaration',
    requirement: 'A sulfite declaration is required when total sulfur dioxide is at least 10 ppm.',
    authorities: ['27 CFR 5.63 and 5.76', DS_GUIDANCE],
    appliesWhen: { description: 'Sulfites are present at 10 ppm or more.', all: [{ fact: 'sulfitesPpm', operator: 'gte', value: 10 }] },
    requiredFacts: ['sulfitesPpm', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['formula', 'supporting_document', 'label_artwork'],
    evaluation: ['Verify an authorized sulfite declaration and applicable formatting.'],
    missingContext: 'Request formula or analysis data; do not infer sub-10 ppm from a missing declaration.',
    reviewerCard: true,
  },
  {
    id: 'spirits.aspartame',
    category: 'distilled_spirits',
    title: 'Aspartame declaration',
    requirement: 'A product containing aspartame must bear the prescribed declaration.',
    authorities: ['27 CFR 5.63 and 5.77', DS_GUIDANCE],
    appliesWhen: { description: 'The formula contains aspartame.', all: [{ fact: 'containsAspartame', operator: 'equals', value: true }] },
    requiredFacts: ['containsAspartame', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Compare the declaration with the prescribed wording and formatting.'],
    missingContext: 'Request formula ingredients when aspartame status is unavailable.',
    reviewerCard: true,
  },

  {
    id: 'wine.under-seven-routing',
    category: 'wine',
    title: 'Wine below 7% TTB jurisdiction routing',
    requirement: 'Wine below 7% alcohol by volume is outside TTB FAA Act COLA jurisdiction; SODAPOP must route it without implementing FDA rules.',
    authorities: ['https://www.ttb.gov/regulated-commodities/beverage-alcohol/wine/7percentorless'],
    appliesWhen: { description: 'Wine contains less than 7% alcohol by volume.', all: [{ fact: 'alcoholContent', operator: 'gt', value: 0 }, { fact: 'alcoholContent', operator: 'lte', value: 6.999 }] },
    requiredFacts: ['alcoholContent', 'source'],
    evidenceSources: ['colas_online', 'supporting_document', 'derived'],
    evaluation: ['Stop the Part 4 COLA rule path.', 'Explain the TTB boundary and retain only applicable TTB Part 16/24 information.'],
    missingContext: 'Require ABV before deciding whether TTB has COLA jurisdiction.',
    reviewerCard: true,
  },
  {
    id: 'wine.brand-name',
    category: 'wine',
    title: 'Brand name',
    requirement: 'Wine at 7% or more must bear the application brand name without creating a misleading impression.',
    authorities: ['27 CFR 4.33', WINE_GUIDANCE],
    appliesWhen: { description: 'Wine is within Part 4 jurisdiction.', all: [{ fact: 'alcoholContent', operator: 'gte', value: 7 }] },
    requiredFacts: ['brandName', 'labelSet'],
    evidenceSources: ['form_5100_31', 'colas_online', 'label_artwork'],
    evaluation: ['Compare application and artwork brand names.', 'Evaluate legibility and misleading implications.'],
    missingContext: 'Recommend Fail if the brand or label evidence is absent.',
    reviewerCard: true,
  },
  {
    id: 'wine.class-type-designation',
    category: 'wine',
    title: 'Class, type, or composition designation',
    requirement: 'The brand label must use an authorized wine identity or a truthful and adequate statement of composition.',
    authorities: ['27 CFR 4.34', WINE_GUIDANCE],
    appliesWhen: { description: 'Wine is within Part 4 jurisdiction.', all: [{ fact: 'alcoholContent', operator: 'gte', value: 7 }] },
    requiredFacts: ['labelClassType', 'formulaClassType', 'formulaCompositionStatement', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork', 'derived'],
    evaluation: ['Compare the designation with the applicable standard or formula.', 'Check direct conjunction and consistent lettering where required.'],
    missingContext: 'Use the standard when possible; otherwise identify missing formula/composition evidence.',
    reviewerCard: true,
  },
  {
    id: 'wine.brand-label-placement',
    category: 'wine',
    title: 'Required brand-label information',
    requirement: 'Brand name, class/type, and any required appellation or foreign-wine percentage must appear on the brand label.',
    authorities: ['27 CFR 4.32 and 4.34', `${WINE_DETAIL}/wine-labeling-brand-label`],
    appliesWhen: { description: 'Wine is within Part 4 jurisdiction.', all: [{ fact: 'alcoholContent', operator: 'gte', value: 7 }] },
    requiredFacts: ['labelSet'],
    evidenceSources: ['colas_online', 'label_artwork', 'derived'],
    evaluation: ['Identify the brand label and verify all triggered brand-label elements occur there.'],
    missingContext: 'Request label-role or complete artwork evidence rather than inferring the brand label.',
    reviewerCard: true,
  },
  {
    id: 'wine.alcohol-content',
    category: 'wine',
    title: 'Alcohol content',
    requirement: 'Wine over 14% requires numerical alcohol content; wine from 7-14% may use an authorized table/light-wine designation in lieu of a number.',
    authorities: ['27 CFR 4.36', 'https://www.ttb.gov/regulated-commodities/beverage-alcohol/wine/wine-labeling-alcohol-content'],
    appliesWhen: { description: 'Wine is within Part 4 jurisdiction.', all: [{ fact: 'alcoholContent', operator: 'gte', value: 7 }] },
    requiredFacts: ['alcoholContent', 'labelClassType', 'labelSet'],
    evidenceSources: ['colas_online', 'label_artwork'],
    evaluation: ['Select the 7-14% or over-14% branch.', 'Validate numerical or permitted substitute wording, range, taxable-grade boundaries, and tolerance.'],
    missingContext: 'Require actual application ABV before selecting the branch.',
    reviewerCard: true,
  },
  {
    id: 'wine.name-address',
    category: 'wine',
    title: 'Name and address',
    requirement: 'The label must carry the appropriate domestic bottler/packer or imported-product responsible-party statement and permit-matching address.',
    authorities: ['27 CFR 4.35', `${WINE_DETAIL}/wine-labeling-name-and-address`],
    appliesWhen: { description: 'Wine is within Part 4 jurisdiction.', all: [{ fact: 'alcoholContent', operator: 'gte', value: 7 }] },
    requiredFacts: ['source', 'applicantName', 'applicantAddress', 'permitName', 'permitAddress', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['form_5100_31', 'permit_or_brewers_notice', 'label_artwork'],
    evaluation: ['Select domestic/import wording.', 'Compare name, trade name, city, State, operation phrase, size, and legibility.'],
    missingContext: 'Recommend Fail when required responsible-party or permit context is absent.',
    reviewerCard: true,
  },
  {
    id: 'wine.net-contents',
    category: 'wine',
    title: 'Net contents',
    requirement: 'The wine container must bear net contents in an authorized form.',
    authorities: ['27 CFR 4.37', WINE_GUIDANCE],
    appliesWhen: { description: 'Wine is within Part 4 jurisdiction.', all: [{ fact: 'alcoholContent', operator: 'gte', value: 7 }] },
    requiredFacts: ['netContents', 'containerVolumeMl', 'labelSet', 'bottleMarkings'],
    evidenceSources: ['colas_online', 'label_artwork'],
    evaluation: ['Search labels and authorized container markings.', 'Normalize units and compare quantity and format.'],
    missingContext: 'Recommend Fail when neither artwork nor documented markings contain the statement.',
    reviewerCard: true,
  },
  {
    id: 'wine.appellation',
    category: 'wine',
    title: 'Appellation of origin',
    requirement: 'A valid appellation must appear on the brand label when triggered and must be supported by origin and production facts.',
    authorities: ['27 CFR 4.23-4.27 and 4.34', `${WINE_DETAIL}/wine-labeling-appellation-of-origin`],
    appliesWhen: { description: 'The application or artwork uses a varietal, vintage, semi-generic, estate-bottled, or other appellation-triggering claim.', any: [{ fact: 'wineAppellation', operator: 'present' }, { fact: 'wineVarietals', operator: 'present' }, { fact: 'wineVintage', operator: 'present' }, { fact: 'wineEstateBottledClaim', operator: 'equals', value: true }] },
    requiredFacts: ['wineAppellation', 'wineVarietals', 'wineVintage', 'wineEstateBottledClaim', 'productionFacts', 'labelSet'],
    evidenceSources: ['form_5100_31', 'colas_online', 'supporting_document', 'label_artwork'],
    evaluation: ['Identify the triggering claim.', 'Validate appellation type, required percentage, origin, placement, and conjunction.'],
    missingContext: 'Identify the missing origin/production evidence and do not approve an unsupported appellation.',
    reviewerCard: true,
  },
  {
    id: 'wine.varietal',
    category: 'wine',
    title: 'Grape varietal designation',
    requirement: 'A varietal designation must be authorized, supported by required grape percentages, and accompanied by an appellation.',
    authorities: ['27 CFR 4.23 and 4.91-4.93', 'https://www.ttb.gov/regulated-commodities/beverage-alcohol/wine/grape-variety-designations-on-american-wine-labels'],
    appliesWhen: { description: 'A grape variety appears in the application or as the label designation.', all: [{ fact: 'wineVarietals', operator: 'present' }] },
    requiredFacts: ['wineVarietals', 'wineAppellation', 'productionFacts', 'labelSet'],
    evidenceSources: ['form_5100_31', 'colas_online', 'supporting_document', 'label_artwork'],
    evaluation: ['Compare listed varieties.', 'Validate authorization, percentage support, qualifying statements, and appellation.'],
    missingContext: 'Request varietal percentage and origin records when absent.',
    reviewerCard: true,
  },
  {
    id: 'wine.vintage',
    category: 'wine',
    title: 'Vintage date',
    requirement: 'A vintage claim must be supported by harvest-year percentages and an appropriate appellation.',
    authorities: ['27 CFR 4.27', WINE_GUIDANCE],
    appliesWhen: { description: 'A vintage date appears in the application or artwork.', all: [{ fact: 'wineVintage', operator: 'present' }] },
    requiredFacts: ['wineVintage', 'wineAppellation', 'productionFacts', 'labelSet'],
    evidenceSources: ['colas_online', 'supporting_document', 'label_artwork'],
    evaluation: ['Compare vintage values.', 'Validate harvest-year support and the required appellation.'],
    missingContext: 'Request harvest-year and appellation evidence; do not validate the year from artwork alone.',
    reviewerCard: true,
  },
  {
    id: 'wine.estate-bottled',
    category: 'wine',
    title: 'Estate bottled claim',
    requirement: '“Estate bottled” requires a qualifying viticultural-area appellation and continuous qualifying production on the named estate premises.',
    authorities: ['27 CFR 4.26', `${WINE_DETAIL}/wine-labeling-appellation-of-origin`],
    appliesWhen: { description: 'The label uses “estate bottled.”', all: [{ fact: 'wineEstateBottledClaim', operator: 'equals', value: true }] },
    requiredFacts: ['wineEstateBottledClaim', 'wineAppellation', 'productionFacts', 'labelSet'],
    evidenceSources: ['permit_or_brewers_notice', 'supporting_document', 'label_artwork'],
    evaluation: ['Verify the viticultural-area appellation and continuous estate production facts.'],
    missingContext: 'Treat absent estate-production support as an unsupported claim.',
    reviewerCard: true,
  },
  {
    id: 'wine.foreign-wine-percentage',
    category: 'wine',
    title: 'Percentage of foreign wine',
    requirement: 'A blend of American and foreign wine that refers to foreign wine must state the foreign percentage by volume on the brand label.',
    authorities: ['27 CFR 4.32(a)(4)', WINE_GUIDANCE],
    appliesWhen: { description: 'The product blends American and foreign wine and the label refers to foreign wine.', all: [{ fact: 'wineForeignBlendReferenced', operator: 'equals', value: true }] },
    requiredFacts: ['wineForeignBlendReferenced', 'wineForeignPercentage', 'productionFacts', 'labelSet'],
    evidenceSources: ['formula', 'supporting_document', 'label_artwork'],
    evaluation: ['Compare the labeled percentage with composition facts and verify brand-label placement.'],
    missingContext: 'Request the blend percentages when foreign wine is referenced.',
    reviewerCard: true,
  },
  {
    id: 'wine.country-of-origin',
    category: 'wine',
    title: 'Imported-wine country of origin',
    requirement: 'Imported wine must bear a country-of-origin statement consistent with the review packet.',
    authorities: ['27 CFR 4.32 and 4.34', 'https://www.ttb.gov/regulated-commodities/beverage-alcohol/wine/labelreqimportedwine'],
    appliesWhen: { description: 'Wine is imported and contains at least 7% alcohol.', all: [{ fact: 'source', operator: 'equals', value: 'imported' }, { fact: 'alcoholContent', operator: 'gte', value: 7 }] },
    requiredFacts: ['source', 'importCountryOfOrigin', 'labelSet'],
    evidenceSources: ['form_5100_31', 'supporting_document', 'label_artwork'],
    evaluation: ['Detect and compare country of origin.', 'Flag absence or contradiction without reproducing all CBP law.'],
    missingContext: 'Request the import country rather than treating an unspecified origin as a pass.',
    reviewerCard: true,
  },
  {
    id: 'wine.formula-composition',
    category: 'wine',
    title: 'Formula-approved wine composition',
    requirement: 'A formulated wine must use the approved statement of composition or an acceptable more-specific statement.',
    authorities: ['27 CFR 4.34', WINE_GUIDANCE],
    appliesWhen: { description: 'The approved formula provides a composition statement.', all: [{ fact: 'formulaCompositionStatement', operator: 'present' }] },
    requiredFacts: ['formulaCompositionStatement', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Compare composition wording with the formula and verify brand-label placement.'],
    missingContext: 'Recommend Fail when required formula wording or formula evidence is absent.',
    reviewerCard: true,
  },
  {
    id: 'wine.sulfites',
    category: 'wine',
    title: 'Sulfite declaration',
    requirement: 'Wine containing at least 10 ppm total sulfur dioxide must bear an authorized sulfite declaration.',
    authorities: ['27 CFR 4.32(e)', 'https://www.ttb.gov/regulated-commodities/beverage-alcohol/wine/wine-labeling-declaration-of-sulfites'],
    appliesWhen: { description: 'Sulfites are present at 10 ppm or more.', all: [{ fact: 'sulfitesPpm', operator: 'gte', value: 10 }] },
    requiredFacts: ['sulfitesPpm', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['formula', 'supporting_document', 'label_artwork'],
    evaluation: ['Verify declaration wording, type size, contrast, and separation.'],
    missingContext: 'Require a TTB-acceptable sulfite analysis when the application seeks to omit the declaration.',
    reviewerCard: true,
  },
  {
    id: 'wine.yellow-5',
    category: 'wine',
    title: 'FD&C Yellow No. 5 disclosure',
    requirement: 'Wine containing FD&C Yellow No. 5 must specifically declare it and use a formula-consistent composition statement.',
    authorities: ['27 CFR 4.32(d) and 4.34(a)', `${WINE_DETAIL}/wine-labeling-color-ingredient-disclosures`],
    appliesWhen: { description: 'The formula contains FD&C Yellow No. 5.', all: [{ fact: 'containsYellow5', operator: 'equals', value: true }] },
    requiredFacts: ['containsYellow5', 'formulaCompositionStatement', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Verify the specific declaration, composition wording, size, contrast, and separation.'],
    missingContext: 'Request formula ingredients when color-additive status is unavailable.',
    reviewerCard: true,
  },
  {
    id: 'wine.cochineal-carmine',
    category: 'wine',
    title: 'Cochineal extract or carmine disclosure',
    requirement: 'Wine containing cochineal extract or carmine must specifically declare it and use a formula-consistent composition statement.',
    authorities: ['27 CFR 4.32(d) and 4.34(a)', `${WINE_DETAIL}/wine-labeling-color-ingredient-disclosures`],
    appliesWhen: { description: 'The formula contains cochineal extract or carmine.', all: [{ fact: 'containsCochinealOrCarmine', operator: 'equals', value: true }] },
    requiredFacts: ['containsCochinealOrCarmine', 'formulaCompositionStatement', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Verify the specific declaration, composition wording, size, contrast, and separation.'],
    missingContext: 'Request formula ingredients when color-additive status is unavailable.',
    reviewerCard: true,
  },

  {
    id: 'malt.brand-name',
    category: 'malt_beverage',
    title: 'Brand name',
    requirement: 'The malt beverage must bear the application brand name without creating a misleading impression.',
    authorities: ['27 CFR 7.64', MALT_GUIDANCE],
    appliesWhen: always,
    requiredFacts: ['brandName', 'labelSet'],
    evidenceSources: ['form_5100_31', 'colas_online', 'label_artwork'],
    evaluation: ['Compare the application and artwork brand.', 'Evaluate legibility and misleading implications.'],
    missingContext: 'Recommend Fail if the brand or label evidence is absent.',
    reviewerCard: true,
  },
  {
    id: 'malt.class-type-designation',
    category: 'malt_beverage',
    title: 'Class, type, or specialty designation',
    requirement: 'The label must use a recognized class/type or a fanciful name with a truthful statement of composition for a specialty product.',
    authorities: ['27 CFR 7.141-7.147', `${MALT_GUIDANCE}/malt-beverage-class-and-type`],
    appliesWhen: always,
    requiredFacts: ['alcoholContent', 'labelClassType', 'formulaClassType', 'formulaCompositionStatement', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork', 'derived'],
    evaluation: ['Select the at-least-0.5% or under-0.5% designation branch.', 'Compare identity with trade understanding or formula.', 'Check conjunction and ingredient representation.'],
    missingContext: 'Use the class standards when possible; otherwise identify missing formula/composition evidence.',
    reviewerCard: true,
  },
  {
    id: 'malt.net-contents',
    category: 'malt_beverage',
    title: 'Net contents',
    requirement: 'Net contents must appear in required U.S. units; metric units may be additional but not a substitute.',
    authorities: ['27 CFR 7.70', MALT_GUIDANCE],
    appliesWhen: always,
    requiredFacts: ['netContents', 'containerVolumeMl', 'labelSet', 'bottleMarkings'],
    evidenceSources: ['colas_online', 'label_artwork'],
    evaluation: ['Search labels and authorized container markings.', 'Normalize and compare U.S. quantity and any metric equivalent.'],
    missingContext: 'Recommend Fail when neither artwork nor documented markings contain the statement.',
    reviewerCard: true,
  },
  {
    id: 'malt.name-address',
    category: 'malt_beverage',
    title: 'Name and address',
    requirement: 'The label must carry the appropriate domestic bottler or imported-product statement matching the Brewer’s Notice/basic permit.',
    authorities: ['27 CFR 7.66-7.68', MALT_GUIDANCE],
    appliesWhen: always,
    requiredFacts: ['source', 'applicantName', 'applicantAddress', 'permitName', 'permitAddress', 'containerVolumeMl', 'importBottlingDisposition', 'labelSet'],
    evidenceSources: ['form_5100_31', 'permit_or_brewers_notice', 'supporting_document', 'label_artwork'],
    evaluation: ['Select domestic/import and post-import bottling branches.', 'Compare names, trade names, places, phrases, size, and legibility.'],
    missingContext: 'Recommend Fail when responsible-party or production-disposition context is absent.',
    reviewerCard: true,
  },
  {
    id: 'malt.alcohol-content',
    category: 'malt_beverage',
    title: 'Alcohol content',
    requirement: 'Alcohol by volume is mandatory when alcohol comes from covered added flavors/non-beverage ingredients; any displayed statement must use permitted form and tolerances.',
    authorities: ['27 CFR 7.63(a)(3) and 7.65', `${MALT_GUIDANCE}/malt-beverage-alcohol-content`],
    appliesWhen: { description: 'Alcohol content is mandatory from formulation or appears voluntarily on the artwork.', any: [{ fact: 'maltAlcoholFromAddedIngredients', operator: 'equals', value: true }, { fact: 'labelAlcoholStatementPresent', operator: 'equals', value: true }] },
    requiredFacts: ['maltAlcoholFromAddedIngredients', 'labelAlcoholStatementPresent', 'alcoholContent', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['colas_online', 'formula', 'label_artwork'],
    evaluation: ['Determine whether the statement is mandatory.', 'Compare ABV, precision, abbreviations, type-size bounds, and tolerance.'],
    missingContext: 'Request formula alcohol-contribution facts instead of assuming the statement is optional.',
    reviewerCard: true,
  },
  {
    id: 'malt.specialty-composition',
    category: 'malt_beverage',
    title: 'Specialty fanciful name and composition',
    requirement: 'A malt beverage specialty must bear a fanciful name and adequate formula-consistent statement of composition.',
    authorities: ['27 CFR 7.147', `${MALT_GUIDANCE}/malt-beverage-class-and-type`],
    appliesWhen: { description: 'The product is a malt beverage specialty.', all: [{ fact: 'maltSpecialtyProduct', operator: 'equals', value: true }] },
    requiredFacts: ['maltSpecialtyProduct', 'fancifulName', 'formulaCompositionStatement', 'labelSet'],
    evidenceSources: ['form_5100_31', 'formula', 'label_artwork'],
    evaluation: ['Compare fanciful name and composition statement with application and formula.', 'Verify flavors, colors, and artificial sweeteners are adequately represented.'],
    missingContext: 'Recommend Fail if required specialty identity or formula evidence is absent.',
    reviewerCard: true,
  },
  {
    id: 'malt.alcohol-characterization-claims',
    category: 'malt_beverage',
    title: 'Low, non-alcoholic, and alcohol-free claims',
    requirement: 'Alcohol-characterization claims must meet the applicable thresholds and carry required adjacent wording.',
    authorities: ['27 CFR 7.65(d)-(f)', `${MALT_GUIDANCE}/malt-beverage-alcohol-content`],
    appliesWhen: { description: 'Artwork makes a low/reduced, non-alcoholic, or alcohol-free claim.', all: [{ fact: 'maltAlcoholCharacterizationClaim', operator: 'equals', value: true }] },
    requiredFacts: ['maltAlcoholCharacterizationClaim', 'alcoholContent', 'productionFacts', 'labelSet'],
    evidenceSources: ['colas_online', 'supporting_document', 'label_artwork'],
    evaluation: ['Detect the claim.', 'Apply its ABV threshold and adjacent-statement requirements.'],
    missingContext: 'Do not validate an alcohol-characterization claim without actual alcohol facts.',
    reviewerCard: true,
  },
  {
    id: 'malt.country-of-origin',
    category: 'malt_beverage',
    title: 'Imported-product country of origin',
    requirement: 'Imported malt beverages must bear a country-of-origin statement consistent with the review packet.',
    authorities: ['27 CFR 7.69', `${MALT_GUIDANCE}/malt-beverage-name-and-address-imports`],
    appliesWhen: { description: 'The malt beverage is imported.', all: [{ fact: 'source', operator: 'equals', value: 'imported' }] },
    requiredFacts: ['source', 'importCountryOfOrigin', 'labelSet'],
    evidenceSources: ['form_5100_31', 'supporting_document', 'label_artwork'],
    evaluation: ['Detect and compare the origin statement.', 'Flag absence or contradiction without reproducing all CBP law.'],
    missingContext: 'Request the import country rather than treating an unspecified origin as a pass.',
    reviewerCard: true,
  },
  {
    id: 'malt.import-bottling-disposition',
    category: 'malt_beverage',
    title: 'Imported-product bottling statement',
    requirement: 'Imported malt beverages bottled or further produced in the United States must use the responsible-party statements required for that disposition.',
    authorities: ['27 CFR 7.67-7.68', `${MALT_GUIDANCE}/malt-beverage-name-and-address-imports`],
    appliesWhen: { description: 'The malt beverage is imported and bottled or processed after importation.', all: [{ fact: 'source', operator: 'equals', value: 'imported' }, { fact: 'importBottlingDisposition', operator: 'present' }] },
    requiredFacts: ['importBottlingDisposition', 'permitName', 'permitAddress', 'labelSet'],
    evidenceSources: ['supporting_document', 'permit_or_brewers_notice', 'label_artwork'],
    evaluation: ['Select imported-and-bottled, separately bottled, or domestically produced wording based on post-import activity.'],
    missingContext: 'Require post-import production facts before approving the responsible-party wording.',
    reviewerCard: true,
  },
  {
    id: 'malt.geographic-designation',
    category: 'malt_beverage',
    title: 'Geographically significant designation',
    requirement: 'A geographically significant malt beverage designation must reflect the true place of production or be properly qualified.',
    authorities: ['27 CFR 7.144', `${MALT_GUIDANCE}/malt-beverage-class-and-type`],
    appliesWhen: { description: 'The class/type or optional identity uses a geographically significant term.', all: [{ fact: 'maltGeographicClaim', operator: 'equals', value: true }] },
    requiredFacts: ['maltGeographicClaim', 'labelClassType', 'productionFacts', 'labelSet'],
    evidenceSources: ['formula', 'supporting_document', 'label_artwork'],
    evaluation: ['Detect geographic identity terms.', 'Compare place of production and required “type,” “style,” or equivalent qualification.'],
    missingContext: 'Do not approve an origin-significant term without production-location evidence.',
    reviewerCard: true,
  },
  {
    id: 'malt.yellow-5',
    category: 'malt_beverage',
    title: 'FD&C Yellow No. 5 disclosure',
    requirement: 'FD&C Yellow No. 5 must be specifically declared when present.',
    authorities: ['27 CFR 7.63(b)', MALT_GUIDANCE],
    appliesWhen: { description: 'The formula contains FD&C Yellow No. 5.', all: [{ fact: 'containsYellow5', operator: 'equals', value: true }] },
    requiredFacts: ['containsYellow5', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Verify the specific declaration and applicable formatting.'],
    missingContext: 'Request formula ingredients when color-additive status is unavailable.',
    reviewerCard: true,
  },
  {
    id: 'malt.cochineal-carmine',
    category: 'malt_beverage',
    title: 'Cochineal extract or carmine disclosure',
    requirement: 'Cochineal extract or carmine must be specifically declared when present.',
    authorities: ['27 CFR 7.63(b)', MALT_GUIDANCE],
    appliesWhen: { description: 'The formula contains cochineal extract or carmine.', all: [{ fact: 'containsCochinealOrCarmine', operator: 'equals', value: true }] },
    requiredFacts: ['containsCochinealOrCarmine', 'containerVolumeMl', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Verify the specific declaration and applicable formatting.'],
    missingContext: 'Request formula ingredients when color-additive status is unavailable.',
    reviewerCard: true,
  },
  {
    id: 'malt.sulfites',
    category: 'malt_beverage',
    title: 'Sulfite declaration',
    requirement: 'A sulfite declaration is required when total sulfur dioxide is at least 10 ppm.',
    authorities: ['27 CFR 7.63(b)(3)', `${MALT_GUIDANCE}/malt-beverage-sulfite-aspartame-declarations`],
    appliesWhen: { description: 'Sulfites are present at 10 ppm or more.', all: [{ fact: 'sulfitesPpm', operator: 'gte', value: 10 }] },
    requiredFacts: ['sulfitesPpm', 'labelSet'],
    evidenceSources: ['formula', 'supporting_document', 'label_artwork'],
    evaluation: ['Verify an authorized declaration and applicable formatting.'],
    missingContext: 'Request formula or analysis data; do not infer sub-10 ppm from a missing declaration.',
    reviewerCard: true,
  },
  {
    id: 'malt.aspartame',
    category: 'malt_beverage',
    title: 'Aspartame declaration',
    requirement: 'A malt beverage containing aspartame must bear the prescribed declaration.',
    authorities: ['27 CFR 7.63(b)(4)', `${MALT_GUIDANCE}/malt-beverage-sulfite-aspartame-declarations`],
    appliesWhen: { description: 'The formula contains aspartame.', all: [{ fact: 'containsAspartame', operator: 'equals', value: true }] },
    requiredFacts: ['containsAspartame', 'labelSet'],
    evidenceSources: ['formula', 'label_artwork'],
    evaluation: ['Compare the declaration with prescribed wording and formatting.'],
    missingContext: 'Request formula ingredients when aspartame status is unavailable.',
    reviewerCard: true,
  },
  {
    id: 'malt.mandatory-language-location',
    category: 'malt_beverage',
    title: 'Mandatory language and acceptable location',
    requirement: 'Mandatory malt beverage information must use the required language and appear on an acceptable label or authorized container marking.',
    authorities: ['27 CFR 7.55 and 7.61', `${MALT_GUIDANCE}/malt-beverage-mandatory-label-information`],
    appliesWhen: always,
    requiredFacts: ['labelSet', 'bottleMarkings'],
    evidenceSources: ['colas_online', 'label_artwork'],
    evaluation: ['Verify English-language requirements and Puerto Rico exception when applicable.', 'Reject mandatory information placed only on excluded surfaces or closures without authorization.'],
    missingContext: 'Require the complete container artwork/layout before approving placement.',
    reviewerCard: true,
  },
] as const satisfies readonly RuleSpecification[]

const commonBase = [
  'common.label-set-completeness',
  'common.health-warning-wording',
  'common.health-warning-format',
  'common.optional-information',
] as const

const commonConditional = [
  'common.formula-labeling-instructions',
  'common.exemption-eligibility',
] as const

export const RULE_SET_SPECIFICATIONS = [
  {
    id: 'distilled-spirits-domestic',
    label: 'Distilled spirits — Domestic',
    description: '27 CFR parts 5 and 16, including conditional formula, composition, age, additive, and production disclosures.',
    productType: 'distilled_spirits',
    source: 'domestic',
    jurisdiction: 'full_cola_review',
    selectionFacts: ['productType', 'source'],
    baseRuleIds: [...commonBase, 'spirits.brand-name', 'spirits.class-type-designation', 'spirits.alcohol-content', 'spirits.same-field-of-vision', 'spirits.name-address', 'spirits.net-contents'],
    conditionalRuleIds: [...commonConditional, 'common.exemption-state-limitation', 'spirits.distinctive-bottle', 'spirits.specialty-composition', 'spirits.significant-solids-alcohol', 'spirits.neutral-spirits-commodity', 'spirits.age-statement', 'spirits.wood-treatment', 'spirits.state-of-distillation', 'spirits.yellow-5', 'spirits.cochineal-carmine', 'spirits.sulfites', 'spirits.aspartame'],
  },
  {
    id: 'distilled-spirits-imported',
    label: 'Distilled spirits — Imported',
    description: 'The imported distilled spirits branch, including origin and importer requirements plus applicable parts 5 and 16 rules.',
    productType: 'distilled_spirits',
    source: 'imported',
    jurisdiction: 'full_cola_review',
    selectionFacts: ['productType', 'source'],
    baseRuleIds: [...commonBase, 'spirits.brand-name', 'spirits.class-type-designation', 'spirits.alcohol-content', 'spirits.same-field-of-vision', 'spirits.name-address', 'spirits.net-contents', 'spirits.country-of-origin'],
    conditionalRuleIds: [...commonConditional, 'spirits.distinctive-bottle', 'spirits.specialty-composition', 'spirits.significant-solids-alcohol', 'spirits.neutral-spirits-commodity', 'spirits.age-statement', 'spirits.wood-treatment', 'spirits.yellow-5', 'spirits.cochineal-carmine', 'spirits.sulfites', 'spirits.aspartame'],
  },
  {
    id: 'wine-7plus-domestic',
    label: 'Wine 7% or more — Domestic',
    description: 'The domestic FAA Act wine COLA branch under 27 CFR parts 4 and 16.',
    productType: 'wine',
    source: 'domestic',
    jurisdiction: 'full_cola_review',
    selectionFacts: ['productType', 'source', 'alcoholContent'],
    baseRuleIds: [...commonBase, 'wine.brand-name', 'wine.class-type-designation', 'wine.brand-label-placement', 'wine.alcohol-content', 'wine.name-address', 'wine.net-contents'],
    conditionalRuleIds: [...commonConditional, 'common.exemption-state-limitation', 'wine.formula-composition', 'wine.appellation', 'wine.varietal', 'wine.vintage', 'wine.estate-bottled', 'wine.foreign-wine-percentage', 'wine.sulfites', 'wine.yellow-5', 'wine.cochineal-carmine'],
  },
  {
    id: 'wine-7plus-imported',
    label: 'Wine 7% or more — Imported',
    description: 'The imported FAA Act wine COLA branch, including importer, origin, and applicable parts 4 and 16 rules.',
    productType: 'wine',
    source: 'imported',
    jurisdiction: 'full_cola_review',
    selectionFacts: ['productType', 'source', 'alcoholContent'],
    baseRuleIds: [...commonBase, 'wine.brand-name', 'wine.class-type-designation', 'wine.brand-label-placement', 'wine.alcohol-content', 'wine.name-address', 'wine.net-contents', 'wine.country-of-origin'],
    conditionalRuleIds: [...commonConditional, 'wine.formula-composition', 'wine.appellation', 'wine.varietal', 'wine.vintage', 'wine.estate-bottled', 'wine.foreign-wine-percentage', 'wine.sulfites', 'wine.yellow-5', 'wine.cochineal-carmine'],
  },
  {
    id: 'wine-under-7-ttb-routing',
    label: 'Wine below 7% — TTB routing',
    description: 'No Part 4 COLA review. Explain the TTB jurisdiction boundary without implementing FDA rules; retain applicable TTB Part 16/24 routing information.',
    productType: 'wine',
    source: 'either',
    jurisdiction: 'ttb_routing_only',
    selectionFacts: ['productType', 'alcoholContent'],
    baseRuleIds: ['wine.under-seven-routing', 'common.health-warning-wording', 'common.health-warning-format'],
    conditionalRuleIds: [],
  },
  {
    id: 'malt-beverage-domestic',
    label: 'Malt beverage — Domestic',
    description: 'The domestic malt beverage COLA branch under 27 CFR parts 7 and 16.',
    productType: 'malt_beverage',
    source: 'domestic',
    jurisdiction: 'full_cola_review',
    selectionFacts: ['productType', 'source'],
    baseRuleIds: [...commonBase, 'malt.brand-name', 'malt.class-type-designation', 'malt.net-contents', 'malt.name-address', 'malt.mandatory-language-location'],
    conditionalRuleIds: [...commonConditional, 'malt.alcohol-content', 'malt.specialty-composition', 'malt.alcohol-characterization-claims', 'malt.geographic-designation', 'malt.yellow-5', 'malt.cochineal-carmine', 'malt.sulfites', 'malt.aspartame'],
  },
  {
    id: 'malt-beverage-imported',
    label: 'Malt beverage — Imported',
    description: 'The imported malt beverage branch, including origin and post-import bottling logic under parts 7 and 16.',
    productType: 'malt_beverage',
    source: 'imported',
    jurisdiction: 'full_cola_review',
    selectionFacts: ['productType', 'source'],
    baseRuleIds: [...commonBase, 'malt.brand-name', 'malt.class-type-designation', 'malt.net-contents', 'malt.name-address', 'malt.country-of-origin', 'malt.mandatory-language-location'],
    conditionalRuleIds: [...commonConditional, 'malt.import-bottling-disposition', 'malt.alcohol-content', 'malt.specialty-composition', 'malt.alcohol-characterization-claims', 'malt.geographic-designation', 'malt.yellow-5', 'malt.cochineal-carmine', 'malt.sulfites', 'malt.aspartame'],
  },
] as const satisfies readonly RuleSetSpecification[]
